// Builds one landing page per city in tools/cities.mjs, e.g. juontaja-helsinki/index.html.
//
//   node tools/build-cities.mjs
//
// index.html is the source of truth for everything the pages share. Blocks
// wrapped in <!-- @shared:name --> … <!-- @/shared:name --> are copied from it,
// so edit them there and re-run this script. The script also writes the city
// links into the footer of every page, and regenerates sitemap.xml.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE, cities } from './cities.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => readFileSync(join(root, f), 'utf8');
const write = (f, text) => {
  mkdirSync(dirname(join(root, f)), { recursive: true });
  writeFileSync(join(root, f), text);
};

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const today = new Date().toISOString().slice(0, 10);

/* ---------- footer city links, written into every page ---------- */

const cityLinks = (prefix, currentSlug) => `<!-- @cities -->
      <nav class="footer__cities" aria-label="Kaupungit">
        <p class="footer__cities-label">Juontaja ja puhuja</p>
        <ul>${cities.map((c) => `<li><a href="${prefix}${c.slug}/"${c.slug === currentSlug ? ' aria-current="page"' : ''}>${esc(c.name)}</a></li>`).join('')}</ul>
      </nav>
      <!-- @/cities -->`;

const replaceCities = (html, prefix, currentSlug) =>
  html.replace(/<!-- @cities -->[\s\S]*?<!-- @\/cities -->/, cityLinks(prefix, currentSlug));

// Refresh the footer links on the home page first, so the copied footer is current.
let home = replaceCities(read('index.html'), '', null);
write('index.html', home);

/* ---------- shared blocks from index.html ---------- */

const shared = (name) => {
  const m = home.match(new RegExp(`<!-- @shared:${name} -->\\n([\\s\\S]*?)\\n<!-- @/shared:${name} -->`));
  if (!m) throw new Error(`index.html has no shared block "${name}"`);
  // City pages live one folder down.
  return m[1]
    .replace(/(src|href)="assets\//g, '$1="../assets/')
    .replace('class="nav__brand" href="#top"', 'class="nav__brand" href="../"');
};

/* ---------- page ---------- */

function renderCity(c) {
  const url = `${SITE}/${c.slug}/`;

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Person',
        '@id': `${SITE}/#tomas`,
        name: 'Tomas Suominen',
        jobTitle: 'Tapahtumajuontaja ja keynote-puhuja',
        url: `${SITE}/`,
      },
      {
        '@type': 'WebPage',
        '@id': `${url}#page`,
        url,
        name: c.title,
        description: c.description,
        inLanguage: 'fi',
        about: { '@id': `${SITE}/#tomas` },
        breadcrumb: { '@id': `${url}#breadcrumb` },
      },
      {
        '@type': 'BreadcrumbList',
        '@id': `${url}#breadcrumb`,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Etusivu', item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: c.name, item: url },
        ],
      },
      ...[
        ['Juonto', 'Tapahtumajuonto'],
        ['Puhujakeikat', 'Keynote-puheenvuoro'],
        ['VIP Hosting', 'VIP-tilaisuuden isännöinti'],
        ['Ääninäyttely', 'Ääninäyttely'],
      ].map(([name, type]) => ({
        '@type': 'Service',
        name: `${name} ${c.inessive}`,
        serviceType: type,
        provider: { '@id': `${SITE}/#tomas` },
        areaServed: c.area.map((a) => ({ '@type': 'City', name: a })),
        url,
      })),
      {
        '@type': 'FAQPage',
        mainEntity: c.faq.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
      },
    ],
  };

  const refs = c.references.length
    ? `
        <div class="city__refs">
          <h3 class="city__subtitle">Keikkoja ${esc(c.inessive)}</h3>
          <ul class="refs">${c.references.map((r) => `
            <li><span class="refs__event">${esc(r.event)}</span><span class="refs__meta">${esc(r.venue)} · ${esc(r.year)}</span></li>`).join('')}
          </ul>
        </div>`
    : '';

  const services = shared('services').replace(
    /(<h2 id="palvelut-otsikko" class="section-title">)[^<]*(<\/h2>)/,
    `$1Palvelut ${esc(c.inessive)}$2`,
  );

  return `<!doctype html>
<html lang="fi">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by tools/build-cities.mjs from tools/cities.mjs and index.html. Edit those, not this file. -->
  <title>${esc(c.title)}</title>
  <meta name="description" content="${esc(c.description)}">
  <link rel="canonical" href="${url}">
  <meta property="og:title" content="${esc(c.title)}">
  <meta property="og:description" content="${esc(c.description)}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:locale" content="fi_FI">
  <meta name="theme-color" content="#2B0A15">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@500;800;900&family=Hanken+Grotesk:ital,wght@0,400;0,500;0,600;1,400;1,500&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../styles.css">
  <script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2).replace(/</g, '\\u003c')}
  </script>
</head>
<body data-city="${esc(c.name)}">
  <a class="skip" href="#sisalto">Siirry sisältöön</a>

${shared('nav')}

  <section class="stage" id="top" data-stage>
    <div class="stage__light" aria-hidden="true"></div>
    <div class="stage__floor" aria-hidden="true"></div>

    <div class="stage__inner">
      <nav class="crumbs" aria-label="Murupolku">
        <a href="../">Etusivu</a><span aria-hidden="true">/</span><span aria-current="page">${esc(c.name)}</span>
      </nav>
      <p class="eyebrow eyebrow--stage">Tomas Suominen · ${esc(c.name)} ja ${esc(c.region)}</p>

      <h1 class="marquee marquee--city">
        <span class="marquee__base">Juontaja<br>${esc(c.illative)}</span>
        <span class="marquee__lit" aria-hidden="true">Juontaja<br>${esc(c.illative)}</span>
      </h1>

      <p class="stage__lede">${esc(c.lede)}</p>

      <div class="stage__actions">
        <a class="btn btn--light" href="#varaa" data-book>Varaa keikka</a>
        <a class="btn btn--ghost" href="#palvelut">Tutustu palveluihin</a>
      </div>
    </div>
  </section>

  <main id="sisalto">
${shared('logos')}

    <!-- City: the part of the page that is only about this city. -->
    <section class="city" aria-labelledby="city-otsikko">
      <div class="wrap">
        <header class="section-head">
          <p class="eyebrow">${esc(c.name)} ja ${esc(c.region)}</p>
          <h2 id="city-otsikko" class="section-title">Tapahtumajuontaja ${esc(c.inessive)}</h2>
        </header>
        <div class="city__grid">
          <div class="city__copy">
            <p class="city__summary">${esc(c.summary)}</p>
            <p class="city__intro">${esc(c.intro)}</p>
            <div class="city__area">
              <p class="svc__label">Alue</p>
              <ul class="chips">${c.area.map((a) => `<li>${esc(a)}</li>`).join('')}</ul>
            </div>
          </div>
          <ul class="usecases">${c.eventTypes.map((e) => `
            <li class="usecase"><h3 class="usecase__title">${esc(e.title)}</h3><p>${esc(e.text)}</p></li>`).join('')}
          </ul>
        </div>${refs}
      </div>
    </section>

${shared('intro')}

${services}

${shared('process')}

    <section class="faq" id="ukk" aria-labelledby="ukk-otsikko">
      <div class="wrap wrap--narrow">
        <header class="section-head">
          <p class="eyebrow">UKK</p>
          <h2 id="ukk-otsikko" class="section-title">Juontaja ${esc(c.inessive)}: usein kysyttyä</h2>
        </header>${c.faq.map((f) => `
        <details class="qa">
          <summary>${esc(f.q)}</summary>
          <p>${esc(f.a)}</p>
        </details>`).join('')}
      </div>
    </section>

    <section class="booking" id="varaa" aria-labelledby="varaa-otsikko">
      <div class="wrap booking__grid">
        <header class="booking__head">
          <p class="eyebrow eyebrow--stage">Varaa keikka</p>
          <h2 id="varaa-otsikko" class="booking__title">Varaa Tomas tapahtumaasi ${esc(c.inessive)}</h2>
        </header>
        <div class="booking__body">
          <p class="booking__lede">Kerro tapahtumastasi kolmella lyhyellä askeleella. Tiedustelu menee suoraan Tomakselle, ja hän vastaa sähköpostiisi.</p>
          <ol class="booking__steps">
            <li><span>1</span>Mitä tarvitset</li>
            <li><span>2</span>Tapahtuman tiedot</li>
            <li><span>3</span>Yhteystiedot</li>
          </ol>
          <a class="btn btn--light btn--lg" href="#varaa" data-book>Aloita tiedustelu</a>
          <p class="booking__hint">Vie noin kaksi minuuttia.</p>
        </div>
      </div>
    </section>
  </main>

${replaceCities(shared('footer'), '../', c.slug)}

${shared('dialog')}

  <script src="../script.js" defer></script>
</body>
</html>
`;
}

for (const c of cities) {
  write(`${c.slug}/index.html`, renderCity(c));
  console.log(`wrote ${c.slug}/index.html`);
}

/* ---------- sitemap ---------- */

const urls = [`${SITE}/`, ...cities.map((c) => `${SITE}/${c.slug}/`)];
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`);
console.log(`wrote sitemap.xml (${urls.length} urls)`);
